# Generated by Django 5.2.6 on 2025-09-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dbbi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('entree', models.CharField(blank=True, max_length=8, null=True)),
                ('sortie', models.CharField(blank=True, max_length=8, null=True)),
                ('travail', models.CharField(blank=True, max_length=8, null=True)),
                ('travail_cumulee', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'myapp_dbbi',
                'unique_together': {('nom', 'date')},
            },
        ),
    ]
