# Generated by Django 5.2.6 on 2025-09-06 11:19

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_functionresult_remove_dbbi_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbbi',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='dbbi',
            name='entree',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dbbi',
            name='sortie',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dbbi',
            name='travail',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dbbi',
            name='travail_cumulee',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
